### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by maelle** [d4tagirl/DuraznoConfMentions#1]
Le falta una descripcion al repo 😉

**Comment by d4tagirl** [comment]
Tenés razón! Nunca les pongo nada 😱 A cambiar eso! Siempre tan atenta 😀 Gracias!!

**Comment by maelle** [comment]
A mi me gustan porque en un vistazo ves de que se trata, y pueden tener emojis! 😀

**Comment by d4tagirl** [comment]
Si! Cómo no me dí cuenta antes! 🙈 Ahora estoy actualizando las descripciones de todos los repos 💅
